services:
  app:
    build:
      context: .
      dockerfile: ./dockerfile
    container_name: project-portofolio-app
    volumes:
      - .:/var/www
    working_dir: /var/www
    networks:
      - laravel

  nginx:
    build:
      context: ./docker/nginx
    container_name: project-portofolio-nginx
    ports:
      - "8001:80"
    volumes:
      - .:/var/www
    depends_on:
      - app
    networks:
      - laravel

networks:
  laravel:
    driver: bridge
