services:
  app:
    build:
      context: .
      dockerfile: ./dockerfile
    container_name: project-portofolio
    ports:
      - "8001:80"
    environment:
      - APP_ENV=${APP_ENV:-production}
      - APP_URL=
      - ASSET_URL=
      - DB_CONNECTION=sqlite
      - DB_DATABASE=/var/www/database/database.sqlite
    volumes:
      - portofolio-data:/var/www/database
      - portofolio-storage:/var/www/storage

volumes:
  portofolio-data:
  portofolio-storage:
